name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: ✨ Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: 🚚 Restore
        run: |
          dotnet restore src/ScanAGator.sln
          dotnet restore src/ImageRatioTool.sln
          dotnet build src/DendriteTracer.sln --no-restore

      - name: 🛠️ Build
        run: |
          dotnet build src/ScanAGator.sln --no-restore
          dotnet build src/ImageRatioTool.sln --no-restore
          dotnet build src/DendriteTracer.sln --no-restore

      - name: 🧪 Test
        run: |
          dotnet test src/ScanAGator.sln --no-build
          dotnet test src/ImageRatioTool.sln --no-build
          dotnet test src/DendriteTracer.sln --no-build
